apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-push-stephan-js-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: build-push-stephan-js
  workspaces:
    - name: stephan-js # this workspace name must be declared in the Pipeline
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 1Gi 